eProsima/Fast-CDR

src/cpp/exceptions/Exception.cpp
test/ResizeTest.cpp
test/SimpleTest.cpp

One warning is actually a bug in the Exception move operator.
The others are uninitialized values.
Warning: before: http://ci.ros2.org/job/ci_osx/626/
Warning after: http://ci.ros2.org/job/ci_osx/628/

fix clang warnings

---

src/cpp/Cdr.cpp

Currently a message with two dynamic sequence fields which are both left empty can not be received by other vendors (Connext, OpenSplice). As far as I understand this is due to a wrong alignment when serializing sequences.
First the number of elements is serialized which is then followed by the elements (9.3.2.5 Sequence, in https://github.com/eProsima/Fast-CDR/blob/master/doc/information/standards/11-11-02-1.pdf). Since the number of elements is unsigned long (4 bytes) the following elements potentially need alignment (9.3.2.1 Alignment). But in the case when the sequence is empty and no elements are being serialized that alignment must not happen.
Therefore this patch make the alignment happen conditionally only when the sequence is not empty. With this fix the message can be …

fix alignment on empty dynamic sequences

---

CMakeLists.txt
src/cpp/CMakeLists.txt

This PR allows users to let CMake decide whether to build shared or static libraries via, enable `EPROSIMA_HONOR_BUILD_SHARED_LIBS` and then use `BUILD_SHARED_LIBS`  to control CMake's behavior.
Update:
Connects to https://github.com/ros2/ros2/issues/306

Control shared/static linking via EPROSIMA_HONOR_BUILD_SHARED_LIBS and BUILD_SHARED_LIBS

---

src/cpp/CMakeLists.txt

The currently built binary for *nix systems doesn't indicate
its ABI version. This causes QA checks in some build systems
(e.g. OpenEmbedded) report an issue.
This patch adds soversion to the library.

Indicate ABI compatibility with soversion

---

src/cpp/FastCdr.rc

If you don't have Microsoft Foundation Classes for C++ install then you get an error like this:
```
C:\Program Files (x86)\Windows Kits\8.1\bin\x86\rc.exe /D WIN32 /D _WINDOWS /D NDEBUG /D FASTCDR_DYN_LINK /D FASTCDR_SOURCE /D "CMAKE_INTDIR=\\\"Release\\
\"" /D fastcdr_EXPORTS /l"0x0409" /I"C:\dev\ros2\src\eProsima\Fast-CDR\include" /IC:\dev\ros2\build\fastcdr\include\fastcdr /nologo /fo"fastcdr.dir\Releas
e\FastCdr.res" C:\dev\ros2\src\eProsima\Fast-CDR\src\cpp\FastCdr.rc
C:\dev\ros2\src\eProsima\Fast-CDR\src\cpp\FastCdr.rc(33): fatal error RC1015: cannot open include file 'afxres.h'. [C:\dev\ros2\build\fastcdr\src\cpp\fastcdr.vcxproj]
```
According to this SO post, this can safely be replaced with `#include "windows.h"`:
http://stackoverflow.com/questions/3566018/cannot-open-include-file …

use windows.h not afxres.h

---

CMakeLists.txt

When you run CMake with the option `--warn-uninitialized` it will complain about it:
```
CMake Warning (dev) at CMakeLists.txt:38:
uninitialized variable 'PROJECT_NAME_LAGE'
```

fix spelling of CMake variable in message

---

include/fastcdr/FastBuffer.h
src/cpp/FastBuffer.cpp
test/ResizeTest.cpp

Connects to https://github.com/eProsima/Fast-CDR/issues/15
As I suppose that resizing to 200 has a special meaning, this PR adds a `reserve` function which lets you pre-initialize the internal memory to a value less than 200. 
It only allows so if the internal memory was not set externally in the constructor as well as was not pre-initialized before (i.e. `m_Buffer == NULL`)

reserve function to reserve initial space for raw buffer

---

include/fastcdr/FastBuffer.h
include/fastcdr/FastCdr.h
include/fastcdr/config.h.in
src/cpp/Cdr.cpp
src/cpp/FastCdr.cpp

Fixes https://github.com/eProsima/Fast-CDR/issues/52
This is an attempt to fix the warnings and test failures in armhf builds.
This ROS2 build shows the warnings that were being raised https://ci.ros2.org/view/All/job/test_ci_linux-armhf/13/warnings23Result/
* Fix `useless-cast` warnings by removing unnecessary use of `uint32_t` when working with `size_t` values
* Fix `cast-align` warnings by doing `memcpy` instead of `reinterpret_cast`s
* Fix test suite by changing `_WIN32` preprocessor guards to also guard ARM32 builds
Please let me know if you would like this split out into separate changes, or if you would prefer to keep it as-is for a single review.

Fix warnings and tests for 32-bit ARM

---

include/fastcdr/FastBuffer.h

I noticed that sometimes `serializeArray` is called with 0 elements. A vector with a capacity of 0 can have data pointing to nullptr. This means that a memcpy call can occur with the first argument as nullptr. According to the [C standard](https://stackoverflow.com/a/5243068), this is undefined behavior.

prevent memcpy with nullptr

---

CMakeLists.txt

Set installation directory correctly for libraries on systems that use LIB_SUFFIX. (This includes the build system on Gentoo.)

Add LIB_SUFFIX support to Cmake build files

---

include/fastcdr/exceptions/BadParamException.h
include/fastcdr/exceptions/Exception.h
include/fastcdr/exceptions/NotEnoughMemoryException.h
src/cpp/exceptions/BadParamException.cpp
src/cpp/exceptions/Exception.cpp
src/cpp/exceptions/NotEnoughMemoryException.cpp

This PR changes the custom exceptions of Fast CDR to keep a `const char *` instead of a `std::string` so they can be made allocation free and noexcept.

Custom exceptions made allocation free and noexcept.

---

include/fastcdr/FastBuffer.h
src/cpp/Cdr.cpp

Here's a suggested fix for https://github.com/eProsima/Fast-CDR/issues/64.
In src/cpp/Cdr.cpp, there appears to be a bug where a `long double **` was set instead of a `long double *`. The warnings were from "-Wstringop-overflow=" in gcc 9.2, after changing to `memcpy.`

fastbuffer memcpy and long double ptr fix

---

include/fastcdr/Cdr.h
include/fastcdr/FastCdr.h
src/cpp/FastBuffer.cpp

For cross-compilation to FreeBSD, `stdlib.h` should be used in place of `malloc.h`, similar to compilations targeting Apple products.

add preprocessing guards for __FreeBSD__ alongside __APPLE__

---

cmake/common/check_configuration.cmake
configure.ac
include/fastcdr/config.h.in
src/cpp/Cdr.cpp

config.h was defining `__BIG_ENDIAN__` macro, setting it to 0 or 1. This can cause problems with other libraries that check endianness by simply `#if defined(__BIG_ENDIAN__)`. In any case, defining macros `__*__` is generally not a good practices, since they are supposed to be reserved for the compiler. The PR changes `__BIG_ENDIAN__` for `FASTCDR_IS_BIG_ENDIAN_TARGET` to internally check for endianness.
This PR is related to eprosima/Fast-DDS#1001.
Signed-off-by: EduPonz <eduardoponz@eprosima.com>

Set and check endianness with FASTCDR_IS_BIG_ENDIAN_TARGET

---

CONTRIBUTING.md
QUALITY.md
README.md

This PR adds a code coverage policy which states that all contributions must at least keep (if not increase) the project's line coverage.
Signed-off-by: EduPonz <eduardoponz@eprosima.com>

Code coverage policy [10027]

---

src/cpp/Cdr.cpp

The deserializeArray() functions for various data types did not write to
the array but to the location of the array pointer instead.
Signed-off-by: Timo Röhling <timo@gaussglocke.de>

Fix invalid memory access during array deserialization

---

CMakeLists.txt

This is to remove a warning that happens on modern CMake
(> 3.19), and shouldn't really cause too many compatibility
problems.
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>
This should fix one of the two warnings on ROS 2 Windows builds: https://ci.ros2.org/view/nightly/job/nightly_win_rel/1769/cmake/

Update the CMake minimum required to 2.8.12.

---

include/fastcdr/Cdr.h
test/SimpleTest.cpp

This PR fixes a `std::bad_alloc` issue when receiving a sequence length greater than the buffer space available.
It also refactors the most basic tests to improve maintainability and reading.

Check sequence lengths when deserializing [10336]

---

src/cpp/Cdr.cpp
src/cpp/FastCdr.cpp

On 32-bit architectures, `std::vector<bool>` has a `max_size()` below 2^32-1,
so the early `resize()` call will throw a length_error exception before
the deserialization code has a chance to throw the
`NotEnoughMemoryException`. This patch moves the `resize()` operation after
the length check, so the correct exception is thrown consistently.

Prevent unexpected length_error exception

---

src/cpp/Cdr.cpp
test/SimpleTest.cpp

Adding tests for method `CDR::read_encapsulation` and doing validity checks inside it.

Validity checks on read_encapsulation [10576]

---

src/cpp/Cdr.cpp
test/SimpleTest.cpp

In SerializeArray Function, the '&' operator was used to a pointer.

[15485] Fix SerializeArray error when swaping the bytes

---

CMakeLists.txt

Visual Studio 19 is supported since CMake 3.14. But with this version, this project has a CMake warning. It is a bug fixed in CMake 3.15.5. Then I've increased the minimum required to 3.15 and our CI is testing against this version.

Increase cmake minimum required [16413]

---

CMakeLists.txt

Since CCache 4.6.1, Visual Studio is supported. But for Debug and RelWithDebugInfo build types, `ccache` needs the compilation option `Z7` instead of `Zi`. This PR adds the CMake feature of detecting the usage of `ccache` and changing the compilation option.

Support ccache on windows

---

include/fastcdr/Cdr.h

Using std::string::assign has an advantage both in binary size and performance:
- [Compiler Explorer](https://godbolt.org/#z:OYLghAFBqd5TKALEBjA9gEwKYFFMCWALugE4A0BIEAZgQDbYB2AhgLbYgDkAjF%2BTXRMiAZVQtGIHgBYBQogFUAztgAKAD24AGfgCsp5eiyahUAUgBMAIUtXyKxqiIEh1ZpgDC6egFc2TEABmAHZydwAZAiZsADk/ACNsUhBZAAd0JWIXJi9ffwN0zOchSOi4tkTk2QdsJ2yRIhZSIly/AJD7bEdipgamolLYhKSU%2B0bm1vyeMf7B8sqUgEp7dB9SVE4uS0Co1F8cAGozQI8lIlIo4GPcMy0AQW3d/ewjk9QzwmFr24f71CQmgcAFQHUjYFiYBoXEwQHxRIiBCwAfSIlgAbAdGCYiEhFscbPcfgA3dAETAHHAqC4SAgAL2wEA%2BIBAZ2hVwsGNZlxRiyOwQJdwOQoOcOEiJRmOYwBxrwAIgctPifsKDhgmGdVQDSCDWXLQeDIedLhAsdLcUr7iquSYUQA6FhKTLAJiM87kSXY82BAUqgD0vutwAlx3lTJZRphrPdppxeO9PzMwVlXGW9G4AFZ%2BAEuDpyOhuB5bLYDkpVusXts%2BOQiNoU8sANYpdO2gCcgRbPC0LZbWgsHOk7cM3Gk/DYQR4tq0wWCLYAHDw0emeCE0TJ0%2BRs7n81x%2BEoQFpq7XlnBYCgMGxUgwk …

Use std::string::assign instead of constructor + move assignment

---

.github/workflows/codeql-analysis.yml

* MacOS 10 runner is not available anymore, so changed it to MacOS 11
* Ubuntu runner changed to 22.04
* Checkout action changed to v3

Improve CodeQL action

---

include/fastcdr/Cdr.h

The changes in this PR allow users to create their own overload of the `<<` and `>>` operators for a data type, and they will be automagically used for vectors and arrays.

[18926] Allow user to override stream operators

---

include/fastcdr/Cdr.h

This PR fixes generated code from `fastddsgen` for sequeces of maps.

Add support of sequences of maps [18924]

---

src/cpp/Cdr.cpp

Under some compilers, optimizations could take away value all together and end up with a serialized buffer that was neither 1 nor 0. This approach removes the need of the stack variable while avoiding the problem

Adapt serialize bool

---

CMakeLists.txt
doxyfile.in

This PR adds a new CMake option `GENERATE_PDF_DOC` to configure the doxyfile in order to generate the intermediate files required to generate the API reference in PDF format. This PR also includes the required changes in the CMakeLists.txt to properly generate and install this document.

[19461] Fix Fast CDR API reference PDF generation

---

include/fastcdr/Cdr.h

as described in cppreference (https://en.cppreference.com/w/cpp/container/array) prior to CWG 1270 revision std::array was required to be initialized using double braces, the QNX SDP 7.0's qcc 5.4 is one of these compilers and compilation errors arise without this patch.
Signed-off-by: Utkan Kılıç utkankilic@gmail.com

fix for non CWG 1270 revision compliant compilers (e.g. QNX qcc 5.4)

---

.github/workflows/mirror.yml
CMakeLists.txt

This PR
1. Bumps the project version to 2.1.0
2. Adds a mirror workflow so that the latest version branch is kept up to date with master.
This is necessary to transition to a branching model similar to Fast DDS', where master is kept as a development branch, and each minor version has a corresponding X.Y.x branch so we can handle backports and releases in a more consistent manner.

[19902] Bump version to 2.1.0

---

CMakeLists.txt
test/cmake/CMakeLists.txt

Reduce CMake minimum version required for Fast DDS compatibility against RHEL 9.

[20176] Downgrade cmake version

---

.github/workflows/fastcdr-test.yml
cmake/testing/GoogleTest.cmake

This PR:
* Refactors the build_and_test workflow so it becomes full multiplatform leveraging eProsima-CI
* Fixes the CMake version used in CI
* Adds a `windows-2019` runner to the list of tests
* Adds a Test summary step to the build_and_test workflow
* Adds a Test reporting step to the build_and_test workflow
* Correctly requires CMake 3.22 for testing
Depends on:
* eProsima/eProsima-CI#56

[20411] Migrate to eProsima-CI

---

fastcdr.repos
include/fastcdr/Cdr.h
include/fastcdr/CdrSizeCalculator.hpp
src/cpp/Cdr.cpp
src/cpp/CdrSizeCalculator.cpp
test/cdr/CMakeLists.txt
test/cdr/array_as_std_vector.cpp

This PR adds API for encoding/decoding a `std::vector` as an array. This API is needed for Fast DDS 3.0 Dynamic Types.

Support serializing a std::vector as an array.

---

.github/workflows/config/colcon.meta
.github/workflows/fastcdr-test.yml

This PR adds macOS 13 to the list of platforms tested in Github CI. Depends on:
* eProsima/eProsima-CI#44
@mergifyio backport 1.1.x 1.0.x

[20091] Add macOS to gihub actions testing

---

include/fastcdr/CdrSizeCalculator.hpp

There is no specialization for `std::vector<bool>` which doesn't contains `data()` function. This PR introduces this specialization.

On CdrSizeCalculator, fix std::vector<bool> as array

---

cmake/common/find_or_add_gtest.cmake
colcon.pkg
package.xml
test/CMakeLists.txt

This PR adds support for building Fast CDR within an ament context (as is the ROS 2 CI).
Since Fast CDR v2.0.0, the CMake option to build the tests is the CMake standard `-DBUILD_TESTING=ON`. When trying to introduce Fast CDR v2 in ROS 2, ROS 2 CI was failing because that CI builds all packages with `-DBUILD_TESTING=ON`, and in that context Fast CDR could not find GTest because is not installed in the system.
In the ROS 2 ecosystem, there are vendor packages within ament for GTest, which are the ones the CI is using. However, Fast CDR's CMakeLists.txt was doing a plain `find_package(GTest REQUIRED)`, and thus failing. In order to find GTest in that context, ament's infrastructure needs to be used. This PR:
1. Adds a package.xml to Fast CDR for ROS 2 packaging. This means that when Fast …

[20328] Add support for building tests within an ament context

---

.github/workflows/codeql-analysis.yml
.github/workflows/fastcdr-test.yml
.github/workflows/mirror.yml
CMakeLists.txt
package.xml

This PR bumps Fast CDR version to 2.2.0 and updates the corresponding workflows

[20494] Bump version to 2.2.0

---

fastcdr.repos

This PR sets 2.1.x as version in fastcdr.repos

[20494] Set 2.1.x as version in fastcdr.repos

---

CMakeLists.txt

This PR avoids building the tests if CMake < 3.22 even when specified via CMake option.

[20327] Do not build test if CMake < 3.22

---

package.xml

After https://github.com/ros2/ros2/pull/1530 has been merged, following ROS 2 [Ubuntu (source)](https://docs.ros.org/en/rolling/Installation/Alternatives/Ubuntu-Development-Setup.html#ubuntu-source) installation instructions fails in step `rosdep install` with the following error:
```
Error(s) in package '/root/ros2_ws/src/eProsima/Fast-CDR/package.xml':
Error(s):
- The "license" tag must not have the following attributes: file
```
This PR fixes that issue by changing the `format` of the `package` tag to version 3.

Change version in package.xml format

---

test/cdr/ResizeTest.cpp
test/cdr/SimpleTest.cpp

When building the tests with g++ 13.2.0, it complains that the EXPECT_LONG_DOUBLE_EQ macro has no effect. That ends up being true; because it is just a x == y, with no EXPECT statement around it, it actually does nothing.
Here, I just remove this macro because it is unnecessary; we can just do EXPECT_TRUE(x == y) and get the same effect with less code.
This is targeted at the 2.2.x branch because that is what we are using in ROS 2, but this applies equally to the master branch.

Fix a compile warning with g++ 13.2.0.

---

CMakeLists.txt
package.xml

This PR bumps Fast CDR version to 2.2.2

[21209] Bump version to 2.2.2

---

.github/pull_request_template.md
.github/workflows/codeql-analysis.yml

macOS-11 runner images are discontinued, so CodeQL jobs are failing cause they cannot pick a mac runner. This PR changes the runner image to macOS-13, which is still active.
@Mergifyio backport 2.2.x 2.1.x 1.0.x
- _N/A_: Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- _N/A_: Changes are API compatible. 

[21286] Run CodeQL on macOS-13 instead of 11

---

.github/workflows/nightly-mac-ci.yml
.github/workflows/nightly-ubuntu-ci.yml
.github/workflows/nightly-windows-ci.yml

The 2.1.x branch is associated to Fast DDS 2.13.x, wich is now EOL.
This PR removes the nightly jobs for that version

[21309] Remove 2.1.x branch from nightly jobs

---

.github/pull_request_template.md
.github/workflows/codeql-analysis.yml
RELEASE_SUPPORT.md

This PR sets 2.1.x (associated to Fast DDS 2.13.x) as EOL
- **N/A** Check CI results: changes do not issue any warning.
- **N/A** Check CI results: CI pass and failing tests are unrelated with the …

[21310] Set 2.1.x (Fast DDS 2.13.x) as EOL

---

CMakeLists.txt
package.xml

This PR bumps Fast CDR version to 2.2.3
- _N/A_ Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- _N/A_ Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- _N/A_ Changes are API compatible. 
- _N/A_ Applicable backports have been included in the description.

[21365] Bump version to 2.2.3

---

include/fastcdr/Cdr.h
test/cdr/SimpleTest.cpp

A `map<T, string>` was not being cleared before deserializing in `XCDRv1`. Test and fix included. Thanks @fschoenm for the report and @MiguelCompany for the analysis.
@Mergifyio backport 2.2.x 1.0.x
Fixes eProsima/Fast-DDS/issues/5136

[21556] Bugfix: clear map before deserializing with string as values in XCRv1

---

include/fastcdr/CdrSizeCalculator.hpp
src/cpp/Cdr.cpp
test/xcdr/CMakeLists.txt
test/xcdr/appendable.cpp
test/xcdr/final.cpp
test/xcdr/mutable.cpp

This PR fixes encoding/decoding of a structure with an inner structure with different extensibility.
```omg-idl
@appendable
struct InnerAppendableStructure
{
@id(3)
unsigned long value1;
@id(16) @optional
unsigned long value2;
};
@mutable
struct MutableWithInnerAppendableStruct
{
@id(1)
unsigned long value1;
@id(2)
InnerAppendableStructure value2;
};
```
- *N/A* Any new/modified methods have been properly documented using Doxygen. 
- *N/A* New feature has been added to the `versions.md` file (if applicable).
- *N/A* Applicable backports have been included in the description.

[21785] Fix encoding/decoding when inner structure has different extensibility

---

include/fastcdr/CdrSizeCalculator.hpp
src/cpp/CdrSizeCalculator.cpp
test/xcdr/basic_types.cpp

It was detected that CdrSizeCalculator adds 4 bytes extra when calculating a fixed string member of a `@mutable` structure in XCdrv2. For example:
```omg-idl
@mutable
struct FixedStringMember
{
string<20> var;
};
```
- *N/A* Any new/modified methods have been properly documented using Doxygen. 
- *N/A* New feature has been added to the `versions.md` file (if applicable).
- *N/A* Applicable backports have been included in the description.

[21795] CdrSizeCalculator adds 4 bytes extra in a fixed string member of mutable structure in XCDRv2

---

.github/pull_request_template.md

The PR template shows as possible branches to backport the current 2.2.x branch instead of 2.1.x.
This PR fixes it.
- **N/A** Check CI results: changes do not issue any warning.
- **N/A** Check CI …

Fix supported branches in PR template backports section

---

include/fastcdr/Cdr.h
src/cpp/Cdr.cpp
test/xcdr/appendable.cpp
test/xcdr/basic_types.cpp
test/xcdr/external.cpp
test/xcdr/final.cpp
test/xcdr/mutable.cpp
test/xcdr/optional.cpp
test/xcdr/xcdrv1.cpp
test/xcdr/xcdrv2.cpp

According to DDS X-Types 1.3, least significant two bits should contain the possible padding in a encoded stream. This PR adds this functionality.
- *N/A* Any new/modified methods have been properly documented using Doxygen. 
- *N/A* Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- *N/A* New feature has been added to the `versions.md` file (if applicable).
- *N/A* Applicable backports have been included in the description.

[22041] Support setting and encoding options with least significant bits set with possible padding

---

include/fastcdr/Cdr.h
include/fastcdr/FastCdr.h
src/cpp/Cdr.cpp
test/cdr/SimpleTest.cpp

This addresses #69 and #214 by explicitly failing to serialize a string that contains null characters, instead of silently discard the last part of the string.
@Mergifyio backport 2.1.x 1.0.x
**Note:** I'm not sure whether we should backport this to 1.x.

[21362] Fail when trying to serialize `std::string` with null characters on its content

---

include/fastcdr/Cdr.h
src/cpp/Cdr.cpp

Fix: function definition is marked dllimport

---

include/fastcdr/Cdr.h
include/fastcdr/FastCdr.h
test/cdr/SimpleTest.cpp

PR #245 introduced a regression that made nightlies of Fast DDS 2.14.x fail. The serialization of empty strings should consist of a length=1 followed by a single null character.
This adds a regression test and removes the check for empty strings in the serialization code.
- _N/A_ Applicable backports have been included in the description.

[22329] Serialize single null-character for empty strings

---

include/fastcdr/xcdr/detail/optional.hpp

Fixes a compile error with Visual Studio 2015.
Steps to reproduce (tested on current `master`)
```
git clone <repo> && cd <repo>
cmake -G"Visual Studio 14 2015 Win64" ..
cmake --build .
```
Will result in the following output
```
D:\projects\Fast-CDR\build>cmake -G"Visual Studio 14 2015 Win64" ..
-- Setting build type to 'Release' as none was specified.
-- Tests not compiled by default
-- Selecting Windows SDK version 10.0.14393.0 to target Windows 10.0.22631.
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- …
```

[21619] Fix C2512 compile error with Visual Studio 2015

---

include/fastcdr/Cdr.h
include/fastcdr/FastCdr.h

At deserialize of fixed_string (cdr) or string (fastcdr) temporary std::string was used which may allocate memory dynamically, which is not desirable or needed especially if using fixed_strings.
@Mergifyio backport 1.0.x

Use assign for deserialize instead of temporary std::string

---

include/fastcdr/xcdr/optional.hpp
test/xcdr/optional.cpp

This PR makes `optional` copy/move constructors from other optionals to actuate only if the storage to copy from is engaged.
This prevents undefined behavior in the placement new when copying/moving data that is not initialized. 
Specially, it tends to throw `std::bad_array_new_length` when trying to copy vectors.
@Mergifyio backport 2.2.x

[22876] Make `optional` copy/move constructors actuate only if the storage is engaged

---

include/fastcdr/cdr/fixed_size_string.hpp
test/cdr/fixed_size_string.cpp
test/xcdr/basic_types.cpp

This PR fixes wrong behavior with fixed strings which had a default value longer than the serialized one.
@Mergifyio backport 2.2.x
- N/A Any new/modified methods have been properly documented using Doxygen. 
- N/A New feature has been added to the `versions.md` file (if applicable).

[23683] Fix default fixed-string length bug
