src/cpp/Cdr.cpp, src/cpp/FastCdr.cpp
I added more descriptive error messages for a few thrown exceptions.
=> Better error messages for exceptions

src/cpp/CMakeLists.txt
This pull request modify the library **SOVERSION** in other to by compliant with Fast-RTPS.
=> Modified CMake soversion

cmake/common/check_configuration.cmake
=> support for QNX

src/java/com/eprosima/fastcdr/idl/templates/TypesHeader.stg
=> Refs #5433 Avoid const decl from included files being declared twice. [5445]

configure.ac
=> Bump version to 1.0.12

include/fastcdr/Cdr.h
Fixes https://github.com/eProsima/Fast-RTPS-Gen/issues/30
=> Fixes map deserialization [8262]

include/fastcdr/Cdr.h, include/fastcdr/FastCdr.h, src/cpp/FastBuffer.cpp
VxWorks does not have malloc.h
=> add __VXWORKS__

VERSIONING.md
Add VERSIONING.md file with the versioning policy declaration for this repository
=> Add versioning policy declaration [9380]

.github/dco.yml
=> Not requiring DCO from members

PLATFORM_SUPPORT.md
Add document stating the platforms and OS supported by Fast CDR
=> Platform support

QUALITY.md, README.md
Add Fast CDR Quality Declaration
Update README to link to the Quality Declaration
For more info about Fast CDR Platform support, please refer to #84
For more info about the code style, please refer to eProsima/cpp-style#3
For more info about CONTRIBUTING, please refer to eProsima/policies#2
For more info about the Fast CDR documentation (API reference), please refer to eProsima/all-docs#17
=> Add Quality Declaration [9390]

QUALITY.md, README.md
Signed-off-by: EduPonz <eduardoponz@eprosima.com>
=> Upgrade to QL1

configure.ac
=> Bump version to 1.0.17

.github/workflows/codeql-analysis.yml
This sets-up the github action for code quality scanning.
You can see it in action [here](https://github.com/MiguelCompany/Fast-CDR/actions/runs/400672936)
=> Setting up CodeQL github action

src/cpp/Cdr.cpp, src/cpp/FastCdr.cpp
This should fix the security issues found by CodeQL.
=> Avoid unsafe castings to wchar_t* [10340]

configure.ac
=> Bump version to 1.0.19

configure.ac
=> Bump version to 1.0.20

configure.ac
=> Bump version to 1.0.21

src/cpp/Cdr.cpp, src/cpp/FastCdr.cpp
Signed-off-by: Timothy Parys <tparys@gmail.com>
=> Deallocate arrays with proper destructor

configure.ac
=> [14124] Bump version to 1.0.24

QUALITY.md
=> [15508] Fix broken link to Fast CDR documentation

configure.ac
Signed-off-by: Eduardo Ponz <eduardoponz@eprosima.com>
=> [15600] Bump version to v1.0.25

configure.ac
=> [16440] Bump version to v1.0.26

include/fastcdr/Cdr.h
=> ENG-1265: Fix build with -std=c++20

PLATFORM_SUPPORT.md, README.md, configure.ac
This PR sets the project version to v1.1.0. Additionally:
* Update the platform support
* Closes #103
=> [18858] Bump version to v1.1.0

.github/workflows/fastcdr-test.yml, PLATFORM_SUPPORT.md, README.md, configure.ac
This PR bumps 1.0 version to v1.0.28
=> [19168] Bump version to v1.0.28

.github/workflows/codeql-analysis.yml, .github/workflows/fastcdr-test.yml
With this PR, both workflows are run not only for master but also for 1.0.x
=> Run CI for both master and 1.0.x branches

CMakeLists.txt
This PR bumps the project version to 2.1.1
=> [20105] Bump version to 2.1.1

CMakeLists.txt
This PR should be merged after:
* #183
=> [20055] Bump version to 2.1.2

CMakeLists.txt
This PR should be merged after:
* #187
=> [20176] Bump version to 2.1.3

include/fastcdr/Cdr.h
This PR fixes a warning in VS 2019
=> Fix warning on windows

CMakeLists.txt, package.xml
This bumps the package version to 2.2.1
=> [20693] Bump version to v2.2.1

.github/pull_request_template.md
This PR adds this PR template
- **N/A** Tests pass locally.
=> [20414] Add PR template 

.github/workflows/reusable-ci.yml
The merge metas file eProsima CI action has been removed. This PR removes its usage.
@Mergifyio backport 2.2.x 1.1.x 1.0.x 
=> [21387] Fix windows CI: Avoid usage of removed action

.github/workflows/codeql-analysis.yml
This version CI CodeQL should not contain other branches triggers for CI, neither cron expressions (non-default branch).
This PR removes them  and uses macos 13 as mac os image
- *N/A*: Check CI …
=> [21286] Remove CodeQL cron and other branch triggers

CMakeLists.txt, package.xml
This PR bumps the Fast CDR version to v2.2.4
- **N/A** Check CI results: changes do not issue any warning.
- **N/A** Check CI results: CI pass and failing tests are unrelated with the changes.
=> [21622] Bump version to v2.2.4

CMakeLists.txt, package.xml
This PR bumps the Fast CDR version to v2.2.5
=> [21783] Bump version to v2.2.5

RELEASE_SUPPORT.md
This PR adds EOL CDR versions in RELEASE_SUPPORT.md
- **N/A** Check CI results: changes do not issue any warning.
- **N/A** Check CI results: CI pass and failing tests are unrelated with the …
=> [22175] Add EOL versions in RELEASE_SUPPORT.md

.github/workflows/reusable-ci.yml, .github/workflows/ubuntu-ci.yml
This PR is a port from eProsima/Fast-DDS#5220 to the `Fast CDR` repository. It makes PR labeling based on workflow input.
@Mergifyio backport 1.0.x
=> [22487] Allow run CI on external contributions

.github/pull_request_template.md, .github/workflows/nightly-mac-ci.yml, .github/workflows/nightly-ubuntu-ci.yml, .github/workflows/nightly-windows-ci.yml
This removes the EOL versions from the `backport` comment in the PR template, and the nightly CI jobs.
- _N/A_: Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- _N/A_: Changes are API compatible. 
- _N/A_: Applicable backports have been included in the description.
=> [22103] Remove EOL versions from PR template and nightly jobs

CMakeLists.txt, package.xml
This bumps the version to 2.2.6
- _N/A_: Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- _N/A_: Changes are API compatible. 
- _N/A_: Applicable backports have been included in the description.
- _N/A_: Check CI results: changes do not issue any warning.
- _N/A_: Check CI results: CI pass and failing tests are unrelated with the changes.
=> [21832] Bump version to 2.2.6

.github/pull_request_template.md, .github/workflows/mirror.yml, CMakeLists.txt, package.xml
This PR prepares `master` branch to become 2.3.0
- _N/A_ Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- _N/A_ Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- _N/A_ Changes are API compatible. 
- _N/A_ Applicable backports have been included in the description.
=> [22881] Branch-out 2.3.x

RELEASE_SUPPORT.md
This PR updates the RELEASE_SUPPORT.md file to update versioning of Fast CDR with latest releases of Fast DDS.
- _N/A_ The code follows the style guidelines of this project. 
- _N/A_ Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- _N/A_ Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- _N/A_ Changes are API compatible. 
- _N/A_ Applicable backports have been included in the description.
=> [21427] Add 3.2 to Release Support

CMakeLists.txt, RELEASE_SUPPORT.md, package.xml
Bump version and update release table in preparation for v2.3.1
- _N/A_: Applicable backports have been included in the description.
=> [23520] Prepare for v2.3.1

CMakeLists.txt, RELEASE_SUPPORT.md, package.xml
Bump version and update release table in preparation for v2.3.2
- _N/A_: Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- _N/A_: Changes are API compatible. 
- _N/A_: Applicable backports have been included in the description.
=> [23520] Prepare for v2.3.2
